import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import React from 'react'
import GlobalAudio from '@/components/player/GlobalAudio'

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
})

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
})

export const metadata: Metadata = {
    title: 'muse wave app',
    description: 'Generated by Roman Krasilnikov',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <title>Muse wave</title>
            <body
                className={`${geistSans.variable} ${geistMono.variable} flex flex-col`}>
                {children}
                <GlobalAudio />
            </body>
        </html>
    )
}

